/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SurgeRouteImport } from './routes/surge'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RidesRouteImport } from './routes/rides'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveRidesRouteImport } from './routes/live-rides'
import { Route as KycRouteImport } from './routes/kyc'
import { Route as HeatmapRouteImport } from './routes/heatmap'
import { Route as FraudRouteImport } from './routes/fraud'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ComplaintsRouteImport } from './routes/complaints'
import { Route as IndexRouteImport } from './routes/index'

const SurgeRoute = SurgeRouteImport.update({
  id: '/surge',
  path: '/surge',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RidesRoute = RidesRouteImport.update({
  id: '/rides',
  path: '/rides',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRidesRoute = LiveRidesRouteImport.update({
  id: '/live-rides',
  path: '/live-rides',
  getParentRoute: () => rootRouteImport,
} as any)
const KycRoute = KycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatmapRoute = HeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const FraudRoute = FraudRouteImport.update({
  id: '/fraud',
  path: '/fraud',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/complaints': typeof ComplaintsRoute
  '/customers': typeof CustomersRoute
  '/drivers': typeof DriversRoute
  '/finance': typeof FinanceRoute
  '/fraud': typeof FraudRoute
  '/heatmap': typeof HeatmapRoute
  '/kyc': typeof KycRoute
  '/live-rides': typeof LiveRidesRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/revenue': typeof RevenueRoute
  '/rides': typeof RidesRoute
  '/settings': typeof SettingsRoute
  '/surge': typeof SurgeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/complaints': typeof ComplaintsRoute
  '/customers': typeof CustomersRoute
  '/drivers': typeof DriversRoute
  '/finance': typeof FinanceRoute
  '/fraud': typeof FraudRoute
  '/heatmap': typeof HeatmapRoute
  '/kyc': typeof KycRoute
  '/live-rides': typeof LiveRidesRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/revenue': typeof RevenueRoute
  '/rides': typeof RidesRoute
  '/settings': typeof SettingsRoute
  '/surge': typeof SurgeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/complaints': typeof ComplaintsRoute
  '/customers': typeof CustomersRoute
  '/drivers': typeof DriversRoute
  '/finance': typeof FinanceRoute
  '/fraud': typeof FraudRoute
  '/heatmap': typeof HeatmapRoute
  '/kyc': typeof KycRoute
  '/live-rides': typeof LiveRidesRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/revenue': typeof RevenueRoute
  '/rides': typeof RidesRoute
  '/settings': typeof SettingsRoute
  '/surge': typeof SurgeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/complaints'
    | '/customers'
    | '/drivers'
    | '/finance'
    | '/fraud'
    | '/heatmap'
    | '/kyc'
    | '/live-rides'
    | '/login'
    | '/notifications'
    | '/revenue'
    | '/rides'
    | '/settings'
    | '/surge'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/complaints'
    | '/customers'
    | '/drivers'
    | '/finance'
    | '/fraud'
    | '/heatmap'
    | '/kyc'
    | '/live-rides'
    | '/login'
    | '/notifications'
    | '/revenue'
    | '/rides'
    | '/settings'
    | '/surge'
  id:
    | '__root__'
    | '/'
    | '/complaints'
    | '/customers'
    | '/drivers'
    | '/finance'
    | '/fraud'
    | '/heatmap'
    | '/kyc'
    | '/live-rides'
    | '/login'
    | '/notifications'
    | '/revenue'
    | '/rides'
    | '/settings'
    | '/surge'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComplaintsRoute: typeof ComplaintsRoute
  CustomersRoute: typeof CustomersRoute
  DriversRoute: typeof DriversRoute
  FinanceRoute: typeof FinanceRoute
  FraudRoute: typeof FraudRoute
  HeatmapRoute: typeof HeatmapRoute
  KycRoute: typeof KycRoute
  LiveRidesRoute: typeof LiveRidesRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  RevenueRoute: typeof RevenueRoute
  RidesRoute: typeof RidesRoute
  SettingsRoute: typeof SettingsRoute
  SurgeRoute: typeof SurgeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/surge': {
      id: '/surge'
      path: '/surge'
      fullPath: '/surge'
      preLoaderRoute: typeof SurgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rides': {
      id: '/rides'
      path: '/rides'
      fullPath: '/rides'
      preLoaderRoute: typeof RidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-rides': {
      id: '/live-rides'
      path: '/live-rides'
      fullPath: '/live-rides'
      preLoaderRoute: typeof LiveRidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatmap': {
      id: '/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof HeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fraud': {
      id: '/fraud'
      path: '/fraud'
      fullPath: '/fraud'
      preLoaderRoute: typeof FraudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints': {
      id: '/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof ComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComplaintsRoute: ComplaintsRoute,
  CustomersRoute: CustomersRoute,
  DriversRoute: DriversRoute,
  FinanceRoute: FinanceRoute,
  FraudRoute: FraudRoute,
  HeatmapRoute: HeatmapRoute,
  KycRoute: KycRoute,
  LiveRidesRoute: LiveRidesRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  RevenueRoute: RevenueRoute,
  RidesRoute: RidesRoute,
  SettingsRoute: SettingsRoute,
  SurgeRoute: SurgeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
