/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as RatingsRouteImport } from './routes/ratings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KycRouteImport } from './routes/kyc'
import { Route as IncentivesRouteImport } from './routes/incentives'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as EarningsRouteImport } from './routes/earnings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WalletIndexRouteImport } from './routes/wallet.index'
import { Route as WalletWithdrawRouteImport } from './routes/wallet.withdraw'
import { Route as RideSummaryRouteImport } from './routes/ride.summary'
import { Route as RideRequestRouteImport } from './routes/ride.request'
import { Route as RideActiveRouteImport } from './routes/ride.active'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingsRoute = RatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KycRoute = KycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const IncentivesRoute = IncentivesRouteImport.update({
  id: '/incentives',
  path: '/incentives',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsRoute = EarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletIndexRoute = WalletIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WalletRoute,
} as any)
const WalletWithdrawRoute = WalletWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => WalletRoute,
} as any)
const RideSummaryRoute = RideSummaryRouteImport.update({
  id: '/ride/summary',
  path: '/ride/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const RideRequestRoute = RideRequestRouteImport.update({
  id: '/ride/request',
  path: '/ride/request',
  getParentRoute: () => rootRouteImport,
} as any)
const RideActiveRoute = RideActiveRouteImport.update({
  id: '/ride/active',
  path: '/ride/active',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/earnings': typeof EarningsRoute
  '/history': typeof HistoryRoute
  '/incentives': typeof IncentivesRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/otp': typeof OtpRoute
  '/profile': typeof ProfileRoute
  '/ratings': typeof RatingsRoute
  '/referral': typeof ReferralRoute
  '/support': typeof SupportRoute
  '/wallet': typeof WalletRouteWithChildren
  '/ride/active': typeof RideActiveRoute
  '/ride/request': typeof RideRequestRoute
  '/ride/summary': typeof RideSummaryRoute
  '/wallet/withdraw': typeof WalletWithdrawRoute
  '/wallet/': typeof WalletIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/earnings': typeof EarningsRoute
  '/history': typeof HistoryRoute
  '/incentives': typeof IncentivesRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/otp': typeof OtpRoute
  '/profile': typeof ProfileRoute
  '/ratings': typeof RatingsRoute
  '/referral': typeof ReferralRoute
  '/support': typeof SupportRoute
  '/ride/active': typeof RideActiveRoute
  '/ride/request': typeof RideRequestRoute
  '/ride/summary': typeof RideSummaryRoute
  '/wallet/withdraw': typeof WalletWithdrawRoute
  '/wallet': typeof WalletIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/earnings': typeof EarningsRoute
  '/history': typeof HistoryRoute
  '/incentives': typeof IncentivesRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/otp': typeof OtpRoute
  '/profile': typeof ProfileRoute
  '/ratings': typeof RatingsRoute
  '/referral': typeof ReferralRoute
  '/support': typeof SupportRoute
  '/wallet': typeof WalletRouteWithChildren
  '/ride/active': typeof RideActiveRoute
  '/ride/request': typeof RideRequestRoute
  '/ride/summary': typeof RideSummaryRoute
  '/wallet/withdraw': typeof WalletWithdrawRoute
  '/wallet/': typeof WalletIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/earnings'
    | '/history'
    | '/incentives'
    | '/kyc'
    | '/login'
    | '/notifications'
    | '/otp'
    | '/profile'
    | '/ratings'
    | '/referral'
    | '/support'
    | '/wallet'
    | '/ride/active'
    | '/ride/request'
    | '/ride/summary'
    | '/wallet/withdraw'
    | '/wallet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/earnings'
    | '/history'
    | '/incentives'
    | '/kyc'
    | '/login'
    | '/notifications'
    | '/otp'
    | '/profile'
    | '/ratings'
    | '/referral'
    | '/support'
    | '/ride/active'
    | '/ride/request'
    | '/ride/summary'
    | '/wallet/withdraw'
    | '/wallet'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/earnings'
    | '/history'
    | '/incentives'
    | '/kyc'
    | '/login'
    | '/notifications'
    | '/otp'
    | '/profile'
    | '/ratings'
    | '/referral'
    | '/support'
    | '/wallet'
    | '/ride/active'
    | '/ride/request'
    | '/ride/summary'
    | '/wallet/withdraw'
    | '/wallet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  EarningsRoute: typeof EarningsRoute
  HistoryRoute: typeof HistoryRoute
  IncentivesRoute: typeof IncentivesRoute
  KycRoute: typeof KycRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OtpRoute: typeof OtpRoute
  ProfileRoute: typeof ProfileRoute
  RatingsRoute: typeof RatingsRoute
  ReferralRoute: typeof ReferralRoute
  SupportRoute: typeof SupportRoute
  WalletRoute: typeof WalletRouteWithChildren
  RideActiveRoute: typeof RideActiveRoute
  RideRequestRoute: typeof RideRequestRoute
  RideSummaryRoute: typeof RideSummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratings': {
      id: '/ratings'
      path: '/ratings'
      fullPath: '/ratings'
      preLoaderRoute: typeof RatingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incentives': {
      id: '/incentives'
      path: '/incentives'
      fullPath: '/incentives'
      preLoaderRoute: typeof IncentivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings': {
      id: '/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof EarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/': {
      id: '/wallet/'
      path: '/'
      fullPath: '/wallet/'
      preLoaderRoute: typeof WalletIndexRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/withdraw': {
      id: '/wallet/withdraw'
      path: '/withdraw'
      fullPath: '/wallet/withdraw'
      preLoaderRoute: typeof WalletWithdrawRouteImport
      parentRoute: typeof WalletRoute
    }
    '/ride/summary': {
      id: '/ride/summary'
      path: '/ride/summary'
      fullPath: '/ride/summary'
      preLoaderRoute: typeof RideSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ride/request': {
      id: '/ride/request'
      path: '/ride/request'
      fullPath: '/ride/request'
      preLoaderRoute: typeof RideRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ride/active': {
      id: '/ride/active'
      path: '/ride/active'
      fullPath: '/ride/active'
      preLoaderRoute: typeof RideActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WalletRouteChildren {
  WalletWithdrawRoute: typeof WalletWithdrawRoute
  WalletIndexRoute: typeof WalletIndexRoute
}

const WalletRouteChildren: WalletRouteChildren = {
  WalletWithdrawRoute: WalletWithdrawRoute,
  WalletIndexRoute: WalletIndexRoute,
}

const WalletRouteWithChildren =
  WalletRoute._addFileChildren(WalletRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EarningsRoute: EarningsRoute,
  HistoryRoute: HistoryRoute,
  IncentivesRoute: IncentivesRoute,
  KycRoute: KycRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OtpRoute: OtpRoute,
  ProfileRoute: ProfileRoute,
  RatingsRoute: RatingsRoute,
  ReferralRoute: ReferralRoute,
  SupportRoute: SupportRoute,
  WalletRoute: WalletRouteWithChildren,
  RideActiveRoute: RideActiveRoute,
  RideRequestRoute: RideRequestRoute,
  RideSummaryRoute: RideSummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
