/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWalletRouteImport } from './routes/app/wallet'
import { Route as AppVoiceRouteImport } from './routes/app/voice'
import { Route as AppTripsRouteImport } from './routes/app/trips'
import { Route as AppTrackRouteImport } from './routes/app/track'
import { Route as AppScheduleRouteImport } from './routes/app/schedule'
import { Route as AppSafetyRouteImport } from './routes/app/safety'
import { Route as AppOffersRouteImport } from './routes/app/offers'
import { Route as AppNotificationsRouteImport } from './routes/app/notifications'
import { Route as AppLanguageRouteImport } from './routes/app/language'
import { Route as AppHomeRouteImport } from './routes/app/home'
import { Route as AppFareRouteImport } from './routes/app/fare'
import { Route as AppBookRouteImport } from './routes/app/book'
import { Route as AppAccountRouteImport } from './routes/app/account'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppVoiceRoute = AppVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => AppRoute,
} as any)
const AppTripsRoute = AppTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackRoute = AppTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppSafetyRoute = AppSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => AppRoute,
} as any)
const AppOffersRoute = AppOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppLanguageRoute = AppLanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppFareRoute = AppFareRouteImport.update({
  id: '/fare',
  path: '/fare',
  getParentRoute: () => AppRoute,
} as any)
const AppBookRoute = AppBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/account': typeof AppAccountRoute
  '/app/book': typeof AppBookRoute
  '/app/fare': typeof AppFareRoute
  '/app/home': typeof AppHomeRoute
  '/app/language': typeof AppLanguageRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/offers': typeof AppOffersRoute
  '/app/safety': typeof AppSafetyRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/track': typeof AppTrackRoute
  '/app/trips': typeof AppTripsRoute
  '/app/voice': typeof AppVoiceRoute
  '/app/wallet': typeof AppWalletRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/account': typeof AppAccountRoute
  '/app/book': typeof AppBookRoute
  '/app/fare': typeof AppFareRoute
  '/app/home': typeof AppHomeRoute
  '/app/language': typeof AppLanguageRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/offers': typeof AppOffersRoute
  '/app/safety': typeof AppSafetyRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/track': typeof AppTrackRoute
  '/app/trips': typeof AppTripsRoute
  '/app/voice': typeof AppVoiceRoute
  '/app/wallet': typeof AppWalletRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/account': typeof AppAccountRoute
  '/app/book': typeof AppBookRoute
  '/app/fare': typeof AppFareRoute
  '/app/home': typeof AppHomeRoute
  '/app/language': typeof AppLanguageRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/offers': typeof AppOffersRoute
  '/app/safety': typeof AppSafetyRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/track': typeof AppTrackRoute
  '/app/trips': typeof AppTripsRoute
  '/app/voice': typeof AppVoiceRoute
  '/app/wallet': typeof AppWalletRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/account'
    | '/app/book'
    | '/app/fare'
    | '/app/home'
    | '/app/language'
    | '/app/notifications'
    | '/app/offers'
    | '/app/safety'
    | '/app/schedule'
    | '/app/track'
    | '/app/trips'
    | '/app/voice'
    | '/app/wallet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/app/account'
    | '/app/book'
    | '/app/fare'
    | '/app/home'
    | '/app/language'
    | '/app/notifications'
    | '/app/offers'
    | '/app/safety'
    | '/app/schedule'
    | '/app/track'
    | '/app/trips'
    | '/app/voice'
    | '/app/wallet'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/account'
    | '/app/book'
    | '/app/fare'
    | '/app/home'
    | '/app/language'
    | '/app/notifications'
    | '/app/offers'
    | '/app/safety'
    | '/app/schedule'
    | '/app/track'
    | '/app/trips'
    | '/app/voice'
    | '/app/wallet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/wallet': {
      id: '/app/wallet'
      path: '/wallet'
      fullPath: '/app/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/voice': {
      id: '/app/voice'
      path: '/voice'
      fullPath: '/app/voice'
      preLoaderRoute: typeof AppVoiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trips': {
      id: '/app/trips'
      path: '/trips'
      fullPath: '/app/trips'
      preLoaderRoute: typeof AppTripsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/track': {
      id: '/app/track'
      path: '/track'
      fullPath: '/app/track'
      preLoaderRoute: typeof AppTrackRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/schedule': {
      id: '/app/schedule'
      path: '/schedule'
      fullPath: '/app/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/safety': {
      id: '/app/safety'
      path: '/safety'
      fullPath: '/app/safety'
      preLoaderRoute: typeof AppSafetyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/offers': {
      id: '/app/offers'
      path: '/offers'
      fullPath: '/app/offers'
      preLoaderRoute: typeof AppOffersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/language': {
      id: '/app/language'
      path: '/language'
      fullPath: '/app/language'
      preLoaderRoute: typeof AppLanguageRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/home': {
      id: '/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fare': {
      id: '/app/fare'
      path: '/fare'
      fullPath: '/app/fare'
      preLoaderRoute: typeof AppFareRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/book': {
      id: '/app/book'
      path: '/book'
      fullPath: '/app/book'
      preLoaderRoute: typeof AppBookRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppBookRoute: typeof AppBookRoute
  AppFareRoute: typeof AppFareRoute
  AppHomeRoute: typeof AppHomeRoute
  AppLanguageRoute: typeof AppLanguageRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOffersRoute: typeof AppOffersRoute
  AppSafetyRoute: typeof AppSafetyRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppTrackRoute: typeof AppTrackRoute
  AppTripsRoute: typeof AppTripsRoute
  AppVoiceRoute: typeof AppVoiceRoute
  AppWalletRoute: typeof AppWalletRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppBookRoute: AppBookRoute,
  AppFareRoute: AppFareRoute,
  AppHomeRoute: AppHomeRoute,
  AppLanguageRoute: AppLanguageRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOffersRoute: AppOffersRoute,
  AppSafetyRoute: AppSafetyRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppTrackRoute: AppTrackRoute,
  AppTripsRoute: AppTripsRoute,
  AppVoiceRoute: AppVoiceRoute,
  AppWalletRoute: AppWalletRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
