# Generated by Django 5.2.14 on 2026-06-04 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('driver', 'Driver'), ('admin', 'Admin')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('blacklisted', 'Blacklisted'), ('new', 'New')], default='new', max_length=20)),
                ('wallet_balance', models.FloatField(default=0.0)),
                ('incentive_balance', models.FloatField(default=0.0)),
                ('bonus_balance', models.FloatField(default=0.0)),
                ('referral_code', models.CharField(blank=True, max_length=50)),
                ('referral_abuse_flag', models.BooleanField(default=False)),
                ('online', models.BooleanField(default=False)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('bank_account', models.CharField(blank=True, max_length=100)),
                ('women_priority_match', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=100)),
                ('positive', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(default='open', max_length=20)),
                ('date', models.CharField(max_length=100)),
                ('chat', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.CharField(max_length=255)),
                ('pickup_sub', models.CharField(blank=True, max_length=255)),
                ('dropoff', models.CharField(max_length=255)),
                ('dropoff_sub', models.CharField(blank=True, max_length=255)),
                ('fare', models.FloatField()),
                ('distance', models.FloatField()),
                ('duration', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('pickup', 'Pickup'), ('otp', 'OTP'), ('trip', 'Trip'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('otp', models.CharField(default='1234', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('surge_multiplier', models.FloatField(default=1.0)),
                ('rain_bonus', models.FloatField(default=0.0)),
                ('rating_customer', models.IntegerField(blank=True, null=True)),
                ('rating_driver', models.IntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_rides', to='core.userprofile')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_rides', to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='todo', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('file_data', models.TextField(blank=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('plate_number', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(choices=[('auto', 'Auto'), ('bike', 'Bike')], max_length=20)),
                ('approved', models.BooleanField(default=False)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('pollution_expiry', models.DateField(blank=True, null=True)),
                ('maintenance_days', models.IntegerField(default=30)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='core.userprofile')),
            ],
        ),
    ]
