# Generated by Django 5.2.14 on 2026-06-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_otpverification_email_alter_otpverification_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdocument',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
