# Generated by Django 5.2.14 on 2026-06-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_kycdocument_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_status',
            field=models.CharField(default='PROFILE_INCOMPLETE', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_go_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
