# Generated by Django 5.2.14 on 2026-06-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_account_status_userprofile_can_go_online_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='kyc_documents/'),
        ),
    ]
