# Generated by Django 5.2.14 on 2026-06-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile_sub_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='last_rejected_at',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ride',
            name='rejected_drivers',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ride',
            name='vehicle_type',
            field=models.CharField(default='bike', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('blacklisted', 'Blacklisted'), ('new', 'New')], default='new', max_length=20),
        ),
    ]
