# Generated by Django 5.2.14 on 2026-06-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ride_last_rejected_at_ride_rejected_drivers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_location_update',
            field=models.IntegerField(default=0),
        ),
    ]
