# Generated by Django 5.2.14 on 2026-06-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_dispatch_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='completion_step',
            field=models.IntegerField(default=-1),
        ),
    ]
