# Generated by Django 5.2.14 on 2026-06-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_ride_completion_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='payment_mode',
            field=models.CharField(default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wallet_went_negative_at',
            field=models.IntegerField(default=0),
        ),
    ]
