# Generated by Django 5.2.14 on 2026-06-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_ride_payment_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='women_safety_match',
            field=models.BooleanField(default=False),
        ),
    ]
