# Generated by Django 5.2.14 on 2026-06-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_sosalert_soslocationsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='drop_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='estimated_fare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='ride_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('SCHEDULED', 'Scheduled')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='ride',
            name='scheduled_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='scheduled_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='scheduled_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('pickup', 'Pickup'), ('otp', 'OTP'), ('trip', 'Trip'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('SCHEDULED', 'Scheduled'), ('MATCHING_PENDING', 'Matching Pending'), ('RIDER_ASSIGNED', 'Rider Assigned'), ('DRIVER_EN_ROUTE', 'Driver En Route'), ('DRIVER_ARRIVED', 'Driver Arrived'), ('RIDE_STARTED', 'Ride Started'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
