# Generated by Django 5.2.14 on 2026-06-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_ride_drop_location_ride_estimated_fare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='no_commission_expiry',
            field=models.IntegerField(default=0),
        ),
    ]
