# Generated by Django 5.2.14 on 2026-06-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_userprofile_no_commission_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default='male', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='women_safety_verified',
            field=models.BooleanField(default=False),
        ),
    ]
