# Generated by Django 5.2.14 on 2026-06-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_userprofile_gender_userprofile_women_safety_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='paid', max_length=20),
        ),
    ]
