# Generated by Django 5.2.14 on 2026-06-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_transaction_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('audience', models.CharField(max_length=255)),
                ('sent_count', models.CharField(default='0', max_length=50)),
                ('open_rate', models.CharField(default='0%', max_length=50)),
                ('channel', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
