# Generated by Django 5.2.14 on 2026-06-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='availability_schedule',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notif_incentives',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notif_push',
            field=models.BooleanField(default=True),
        ),
    ]
