# Generated by Django 5.2.14 on 2026-06-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_userprofile_availability_schedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.CharField(max_length=100)),
                ('multiplier', models.FloatField(default=1.0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('recurrence_type', models.CharField(max_length=50)),
                ('weekdays', models.CharField(default='[]', max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'surge_schedules',
            },
        ),
        migrations.CreateModel(
            name='SurgeZoneConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.CharField(max_length=100, unique=True)),
                ('bike_multiplier', models.FloatField(default=1.0)),
                ('auto_multiplier', models.FloatField(default=1.0)),
                ('rain_enabled', models.BooleanField(default=False)),
                ('festival_enabled', models.BooleanField(default=False)),
                ('hotspot_enabled', models.BooleanField(default=False)),
                ('flood_lockdown_enabled', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'surge_zone_config',
            },
        ),
    ]
