# Generated by Django 5.2.14 on 2026-06-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_surgeschedule_surgezoneconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_vehicle_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
