# Generated by Django 5.2.14 on 2026-06-11 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_userprofile_active_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosalert',
            name='ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sos_alerts', to='core.ride'),
        ),
    ]
