# Generated by Django 5.2.14 on 2026-06-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_sosalert_ride'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='pet_friendly',
            field=models.BooleanField(default=False),
        ),
    ]
